### ISSUE TITLE
Port seems to be left blank?

### ISSUE THREAD

**Issue by jrissler** [hashrocket/gatling#8] opened 2016-10-01 17:39 UTC
`Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 375 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: $ mix deps.get (/home/james/charter)
remote: Running dependency resolution
remote: All dependencies up to date
remote: $ mix compile --force (/home/james/charter)
remote: Compiling 49 files (.ex)
remote: warning: unused import Plug.Conn
remote:   web/controllers/auth.ex:3
remote:
remote: warning: unused alias Priority
remote:   web/controllers/ticket_controller.ex:5
remote:
remote: warning: unused alias Sprint
remote:   web/controllers/ticket_controller.ex:6
remote:
remote: Generated charter app
remote: $ mix phoenix.digest -o public/static (/home/james/charter)
remote: Check your digested files at "public/static"
remote: $ mix release --no-confirm-missing (/home/james/charter)
remote: Building release with MIX_ENV=prod.
remote:
remote: You have dependencies (direct/transitive) which are not in :applications!
remote: The following apps should be added to :applications in mix.exs:
remote:
remote:         phoenix_haml => phoenix_haml is missing from charter
remote:         guardian     => guardian is missing from charter
remote:
remote: This is an upgrade, verifying appups exist for updated dependencies..
remote: ==> All dependencies have appups ready for release!
remote: ==> Generated .appup for charter 0.0.1475342942 -> 0.0.1475343466
remote: ==> The release for charter-0.0.1475343466 is ready!
remote: ==> You can boot a console running your release with `$ rel/charter/bin/charter console`
remote: $ service charter upgrade 0.0.1475343466
remote: Release 0.0.1475343466 not found, attempting to unpack releases/0.0.1475343466/charter.tar.gz
remote: Unpacked successfully: "0.0.1475343466"
remote: Generating vm.args/sys.config for upgrade...
remote: sys.config ready!
remote: vm.args ready!
remote: Release 0.0.1475343466 is already unpacked, now installing.
remote: Installed Release: 0.0.1475343466
remote: Made release permanent: "0.0.1475343466"
remote: $ nginx -s reload
remote: nginx: [emerg] invalid port in upstream "localhost:" in /etc/nginx/sites-enabled/charter:10`

`server {
  listen 80;
  server_name www.mydomain.com;

  location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://localhost:;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }`

Any ideas?

**Comment by mrmicahcooper** [comment] 2016-10-02 23:38
I have a couple ideas. First, make sure you are using the most recent version. `0.1.0` should fix this problem. When the upgrade task runs, it would overwrite your nginx config file every time. This should be fixed now.

Here are a couple suggestions to get this fixed:

First, grab the latest version of Gatling with:

 `mix archive.install https://github.com/hashrocket/gatling_archives/raw/master/gatling.ez`

Then

Look in `/etc/init.d/<project_name>` (in your case, it looks like it might be in `/etc/init.d/charter`) for the environment variable `PORT`. That's the port that should be used in this nginx config.

Or

You could delete `/etc/init.d/charter`, `/etc/nginx/sites-available/charter` and `/etc/nginx/sites-enabled/charter` and re-run `mix gatling.deploy <project_name>`

Let me know how that goes. Also as an FYI, the next version of Gatling will allow you to put your own nginx config in your project so you can override this default file if you want.

Hope this helps!

**Comment by jrissler** [comment] 2016-10-03 12:21
@mrmicahcooper Thanks man - that solved it for me. Also love this package - was exactly what I needed to make deployments 1000x easier :) +1 on nginx config override also

I also had to add these to prod.exs (maybe obvious, still new to elixir here):
`  root: ".",
  server: true`

and uncomment: config :phoenix, :serve_endpoints, true

My js + css are working - but I believe that's because I'm using brunch, thinking I can use one of the callbacks or precompile before deploy.
`brunch build --production && MIX_ENV=prod mix phoenix.digest`

**Comment by mrmicahcooper** [comment] 2016-10-03 20:03
@jrissler Yes, you should be able to use the callbacks for that.

I'm super glad you're liking it! Yes, that configuration should be outlined in the guide but if it's not I'll be sure to add it in there. I'm going to keep this issue open until I've confirmed all the documentation mentioned above is included in.

I really appreciate your feedback and I'm glad you're diggin' it. Feel free to add any issues/PR you notice.
Thanks!

**Comment by jrissler** [comment] 2016-10-03 20:05
@mrmicahcooper np - thanks

**Comment by jrissler** [comment] 2016-10-05 11:57
I have a PR for a readme update that I'll submit here in the next day - basically got it all working, just needed to add some newer phoenix setup to prod.exs that I mentioned, then added callback with npm install, brunch build and phoenix.digest.

I did copy your bash + log functions into my callback (since your package isn't in my app and I liked your functions).

**Comment by hafizio** [comment] 2016-10-12 03:40
@jrissler in which callback are you adding the code to compile the javascript? I'm using webpack to compile my assets.

@mrmicahcooper does gatling run the `phoenix.digest` by default or we have to run it ourselves?

Thank you for a great library!

**Comment by colindensem** [comment] 2016-10-12 07:33
Also noticed this and will await @jrissler PR to compare to my notes. I was also making a list of notes against centos7 & whereupon I noticed this ports issue. So ran a ubuntu vm and also noted it. Super work on the project, thank you.

I tried the first approach of reapplying the port, but it is lost each update. Will review the above.

**Comment by jrissler** [comment] 2016-10-12 11:48
@colindensem I noticed the same issue when performing hot upgrades with the port being lost, I would be interested what you find

My PR is submitted - but its really just what I had to do to get Phoenix app running + assets compiled / served via npm / brunch - https://github.com/hashrocket/gatling/pull/13

**Comment by mrmicahcooper** [comment] 2016-10-12 15:41
@hafizio, The mix digest task does get run. I would imagine you want to compile your digest in the `before_mix_digest` callback.

@jrissler I see you added your own `bash` and `log` functions. You shouldn't have to do that. That is a bug that you just pointed out to me. The `deploy.ex` and `upgrade.ex` files should actually be `.exs` files. That way, they don't get compiled by your project and are instead loaded in context of Gatling during a deploy where those functions are already defined. I'm working on a 1.0.0 release that uses Distillery instead of Exrm. I should have it ready today.

**Comment by jrissler** [comment] 2016-10-12 16:48
@mrmicahcooper awesome that sounds good - thanks

**Comment by mrmicahcooper** [comment] 2016-10-12 16:50
Yep! Just released. Please check it out and keep in mind- As of 1.0.0, Gatling uses distillery instead of exrm!

**Closed** 2016-10-12 16:52 UTC
